export const ALL_SUB_INVENTORY_REQUEST = "ALL_SUB_INVENTORY_REQUEST";
export const ALL_SUB_INVENTORY_SUCCESS = "ALL_SUB_INVENTORY_SUCCESS";
export const ALL_SUB_INVENTORY_FAIL = "ALL_SUB_INVENTORY_FAIL";

export const GET_SUB_INVENTORY_REQUEST = "GET_SUB_INVENTORY_REQUEST";
export const GET_SUB_INVENTORY_SUCCESS = "GET_SUB_INVENTORY_SUCCESS";
export const GET_SUB_INVENTORY_FAIL = "GET_SUB_INVENTORY_FAIL";

export const ADD_ITEM_SUBiN_REQUEST = "ADD_ITEM_SUBiN_REQUEST";
export const ADD_ITEM_SUBiN_SUCCESS = "ADD_ITEM_SUBiN_SUCCESS";
export const ADD_ITEM_SUBiN_FAIL = "ADD_ITEM_SUBiN_FAIL";
export const ADD_ITEM_SUBiN_RESET = "ADD_ITEM_SUBiN_RESET";

export const DELETE_SUBiN_REQUEST = "DELETE_SUBiN_REQUEST";
export const DELETE_SUBiN_SUCCESS = "DELETE_SUBiN_SUCCESS";
export const DELETE_SUBiN_FAIL = "DELETE_SUBiN_FAIL";
export const DELETE_SUBiN_RESET = "DELETE_SUBiN_RESET";
