export const ADD_EMPLOYEE_REQUEST = "ADD_EMPLOYEE_REQUEST";
export const ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS";
export const ADD_EMPLOYEE_FAIL = "ADD_EMPLOYEE_FAIL";
export const ADD_EMPLOYEE_RESET = "ADD_EMPLOYEE_RESET";

export const GET_ALL_EMPLOYEE_REQUEST = "GET_ALL_EMPLOYEE_REQUEST";
export const GET_ALL_EMPLOYEE_SUCCESS = "GET_ALL_EMPLOYEE_SUCCESS";
export const GET_ALL_EMPLOYEE_FAIL = "GET_ALL_EMPLOYEE_FAIL";

export const GET_EMPLOYEE_BY_ID_REQUEST = "GET_EMPLOYEE_BY_ID_REQUEST";
export const GET_EMPLOYEE_BY_ID_SUCCESS = "GET_EMPLOYEE_BY_ID_SUCCESS";
export const GET_EMPLOYEE_BY_ID_FAIL = "GET_EMPLOYEE_BY_ID_FAIL";

//employee
export const UPDATE_KITCHEN_EMP_REQUEST = "UPDATE_KITCHEN_EMP_REQUEST";
export const UPDATE_KITCHEN_EMP_SUCCESS = "UPDATE_KITCHEN_EMP_SUCCESS";
export const UPDATE_KITCHEN_EMP_FAIL = "UPDATE_KITCHEN_EMP_FAIL";
export const UPDATE_KITCHEN_EMP_RESET = "UPDATE_KITCHEN_EMP_RESET";

export const ADD_LEAVE_FOR_EMP_REQUEST = "ADD_LEAVE_FOR_EMP_REQUEST";
export const ADD_LEAVE_FOR_EMP_SUCCESS = "ADD_LEAVE_FOR_EMP_SUCCESS";
export const ADD_LEAVE_FOR_EMP_FAIL = "ADD_LEAVE_FOR_EMP_FAIL";
export const ADD_LEAVE_FOR_EMP_RESET = "ADD_LEAVE_FOR_EMP_RESET";

export const DELETE_LEAVE_OF_EMP_REQUEST = "DELETE_LEAVE_OF_EMP_REQUEST";
export const DELETE_LEAVE_OF_EMP_SUCCESS = "DELETE_LEAVE_OF_EMP_SUCCESS";
export const DELETE_LEAVE_OF_EMP_FAIL = "DELETE_LEAVE_OF_EMP_FAIL";
export const DELETE_LEAVE_OF_EMP_RESET = "DELETE_LEAVE_OF_EMP_RESET";

export const ADD_EXTRA_WORK_REQUEST = "ADD_EXTRA_WORK_REQUEST";
export const ADD_EXTRA_WORK_SUCCESS = "ADD_EXTRA_WORK_SUCCESS";
export const ADD_EXTRA_WORK_FAIL = "ADD_EXTRA_WORK_FAIL";
export const ADD_EXTRA_WORK_RESET = "ADD_EXTRA_WORK_RESET";

export const DELETE_EXTRA_WORK_REQUEST = "DELETE_EXTRA_WORK_REQUEST";
export const DELETE_EXTRA_WORK_SUCCESS = "DELETE_EXTRA_WORK_SUCCESS";
export const DELETE_EXTRA_WORK_FAIL = "DELETE_EXTRA_WORK_FAIL";
export const DELETE_EXTRA_WORK_RESET = "DELETE_EXTRA_WORK_RESET";

export const ADD_PERMISSION_TO_EMP_REQUEST = "ADD_PERMISSION_TO_EMP_REQUEST";
export const ADD_PERMISSION_TO_EMP_SUCCESS = "ADD_PERMISSION_TO_EMP_SUCCESS";
export const ADD_PERMISSION_TO_EMP_FAIL = "ADD_PERMISSION_TO_EMP_FAIL";
export const ADD_PERMISSION_TO_EMP_RESET = "ADD_PERMISSION_TO_EMP_RESET";

export const DELETE_PERMISSION_TO_EMP_REQUEST =
  "DELETE_PERMISSION_TO_EMP_REQUEST";
export const DELETE_PERMISSION_TO_EMP_SUCCESS =
  "DELETE_PERMISSION_TO_EMP_SUCCESS";
export const DELETE_PERMISSION_TO_EMP_FAIL = "DELETE_PERMISSION_TO_EMP_FAIL";
export const DELETE_PERMISSION_TO_EMP_RESET = "DELETE_PERMISSION_TO_EMP_RESET";

export const DELETE_EMP_REQUEST = "DELETE_EMP_REQUEST";
export const DELETE_EMP_SUCCESS = "DELETE_EMP_SUCCESS";
export const DELETE_EMP_FAIL = "DELETE_EMP_FAIL";
export const DELETE_EMP_RESET = "DELETE_EMP_RESET";
