// kitchen owner auth
export const GET_KITCHEN_OWNER_REQUEST = "GET_KITCHEN_OWNER_REQUEST";
export const GET_KITCHEN_OWNER_SUCCESS = "GET_KITCHEN_OWNER_SUCCESS";
export const GET_KITCHEN_OWNER_FAIL = "GET_KITCHEN_OWNER_FAIL";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

//employee login
export const EMPLOYEE_LOGIN_REQUEST = "EMPLOYEE_LOGIN_REQUEST";
export const EMPLOYEE_LOGIN_SUCCESS = "EMPLOYEE_LOGIN_SUCCESS";
export const EMPLOYEE_LOGIN_FAIL = "EMPLOYEE_LOGIN_FAIL";

export const EMP_AUTH_REQUEST = "EMP_AUTH_REQUEST";
export const EMP_AUTH_SUCCESS = "EMP_AUTH_SUCCESS";
export const EMP_AUTH_FAIL = "EMP_AUTH_FAIL";
