export const UPLOAD_MENU_IMAGE_REQUEST = "UPLOAD_MENU_IMAGE_REQUEST";
export const UPLOAD_MENU_IMAGE_SUCCESS = "UPLOAD_MENU_IMAGE_SUCCESS";
export const UPLOAD_MENU_IMAGE_FAIL = "UPLOAD_MENU_IMAGE_FAIL";
export const UPLOAD_MENU_IMAGE_RESET = "UPLOAD_MENU_IMAGE_RESET";
