//employee shift - employee action
export const START_SHIFT_REQUEST = "START_SHIFT_REQUEST";
export const START_SHIFT_SUCCESS = "START_SHIFT_SUCCESS";
export const START_SHIFT_FAIL = "START_SHIFT_FAIL";

export const GET_ALL_SHIFT_REQUEST = "GET_ALL_SHIFT_REQUEST";
export const GET_ALL_SHIFT_SUCCESS = "GET_ALL_SHIFT_SUCCESS";
export const GET_ALL_SHIFT_FAIL = "GET_ALL_SHIFT_FAIL";

export const END_SHIFT_REQUEST = "END_SHIFT_REQUEST";
export const END_SHIFT_SUCCESS = "END_SHIFT_SUCCESS";
export const END_SHIFT_FAIL = "END_SHIFT_FAIL";